import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthButton from "@/components/AuthButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex items-center justify-between px-6 py-3 border-b">
          <a href="/" className="font-semibold">Bongo</a>
          <nav className="flex items-center gap-3">
            <a href="/app" className="text-sm hover:underline">Dashboard</a>
            <a href="/gallery" className="text-sm hover:underline">Gallery</a>
            {/* @ts-expect-error Client Component */}
            <AuthButton />
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
