-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Profiles table (extend auth.users)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  created_at timestamptz default now()
);

-- Assets generated by users
create table if not exists public.assets (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references auth.users(id) on delete cascade,
  model_id text not null,
  prompt text,
  status text not null default 'completed',
  fal_job_id text,
  fal_asset_url text,
  storage_path text,
  width int,
  height int,
  cost_cents int,
  created_at timestamptz default now()
);

-- RLS
alter table public.profiles enable row level security;
alter table public.assets enable row level security;

-- Policies
create policy if not exists "Profiles are viewable by owners"
on public.profiles for select
using ( auth.uid() = id );

create policy if not exists "Insert own profile"
on public.profiles for insert
with check ( auth.uid() = id );

create policy if not exists "Assets are viewable by owners"
on public.assets for select
using ( auth.uid() = user_id );

create policy if not exists "Insert own assets"
on public.assets for insert
with check ( auth.uid() = user_id );

create policy if not exists "Update own assets"
on public.assets for update
using ( auth.uid() = user_id );

